version: '3'

services:
  react.app:
    container_name: ${CONTAINER_NAME}
    restart: always
    build: ./docker
    image: react-symfony-docker
    ports:
      - ${APP_PORT}:80
    networks:
      - react
    volumes:
      - ${PWD}/www:/var/www
    env_file:
      - .env

networks: 
  react:
    driver: bridge